services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - runly-net
    env_file: .env
    restart: unless-stopped
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - runly-net
    env_file: .env
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - runly-net
    env_file: .env
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    networks:
      - runly-net
    env_file: .env
    restart: unless-stopped

networks:
  runly-net:
